version: '2'
services:
    nginx:
        build:
            context: ./nginx
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5" 
        volumes:
            - ./ssl:/etc/nginx/ssl
            #- ./nginx/etc/local-8000-service.conf:/etc/nginx/conf.d/local-8000-service.conf
            # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf              
        expose:
            - 80
            - 443
            - 8000
        ports:
            - "80:80"     
            - "443:443"   
            - "8000:8000"
        environment:
            - TZ=Europe/Paris
            - SSL_ENABLED=true
            - LETSENCRYPT=true
            - LE_EMAIL=jordi.escudero@worldline.com
            - LE_FQDN=bloomen.wlilab.eu
            - USER=bloomen
            - PASSWORD=12345
        links:
            - admin-portal
            - api
            - solr
    admin-portal:
        build:
            context: ./admin-portal
            args: 
              CHAINNAME: "MyChain"
              RPC_PORT: 8002
              RPC_USER: "multichainrpc"
              RPC_PASSWORD: "this-is-insecure-change-it"
              MASTER_NODE: "masternode"
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"   
        expose:
            - 80
        ports:
            - "8080:80" 
        links:
            - masternode            
        depends_on:
            - masternode
    api:
        build:
            context: ./api
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"   
        expose:
            - 3000
        ports:
            - "3000:3000"             
        links:
            - slavenode
            - solr
        depends_on:            
            - slavenode            
            - solr
    solr:
        build:
            context: ./solr
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"   
        expose:
            - 8983
        ports:
            - "8983:8983" 
        entrypoint:
            - docker-entrypoint.sh
            - solr-precreate
            - demo-bloomen-registry-claim-m12
    masternode:
        build: ./masternode
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"   
        expose:
            - 7557
            - 8002
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_TARGET_BLOCK_SIZE: target-block-time|30
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
    slavenode:
        build: ./slavenode
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"   
        expose:
            - 7557
            - 8002
        ports:
            - "8002:8002"
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode            
