version: '2'
services:
    nginx:
        build:
            context: ./nginx
        expose:
            - 80
            - 443
        ports:
            - "80:80"     
            - "443:443"     
        links:
            - admin-portal
            - api            
    admin-portal:
        build:
            context: ./admin-portal
            args: 
              CHAINNAME: "MyChain"
              RPC_PORT: 8002
              RPC_USER: "multichainrpc"
              RPC_PASSWORD: "this-is-insecure-change-it"
              MASTER_NODE: "masternode"
        expose:
            - 80
        ports:
            - "8080:80" 
        links:
            - masternode            
        depends_on:
            - masternode
    api:
        build:
            context: ./api
        expose:
            - 3000
        ports:
            - "3000:3000"             
        links:
            - slavenode
            - solr
        depends_on:            
            - slavenode            
            - solr
    solr:
        build:
            context: ./solr            
        expose:
            - 8983
        ports:
            - "8983:8983" 
    masternode:
        build: ./masternode
        expose:
            - 7557
            - 8002
        ports:
            - "8002:8002" 
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_TARGET_BLOCK_SIZE: target-block-time|30
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
    slavenode:
        build: ./slavenode
        expose:
            - 7557
            - 8002
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode            